postgres_host           = "your-postgresql-host"
postgres_admin_user     = "your-admin-username"
postgres_admin_password = "your-admin-password"
vault_address           = "https://vault.yourdomain.com"
db_name                 = "my_database"